#!/bin/bash

cat "qt-bashrc" >> ~/.bashrc

if [[ $1 -eq "full" ]]; then
	touch ~/.me
	echo "Alexandre R Gomes" >> ~/.me
	echo "gomes.bcc@gmail.com | gomes.ar@protonmail.ch | agomes@lasca.ic.unicamp.br" >> ~/.me
fi
